# GitHub Actions를 통한 자동 배포
name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'backend/**' ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: uriwork-fastapi
  REGION: asia-northeast3

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Google Cloud Auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build and Push
      run: |
        gcloud builds submit --tag gcr.io/$PROJECT_ID/$SERVICE_NAME ./backend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --set-env-vars ENVIRONMENT=production \
          --set-env-vars OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
          --set-env-vars FIREBASE_PROJECT_ID="calendar-8e1a2" \
          --set-env-vars VITE_API_BASE_URL="https://uriwork-fastapi-1014872932714.asia-northeast3.run.app" \
          --set-env-vars VITE_CLOUD_RUN_URL="https://uriwork-fastapi-1014872932714.asia-northeast3.run.app"
